# Generated by Django 2.2.12 on 2020-04-27 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning__logs', '0002_entry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name_plural': 'entries'},
        ),
    ]
